/**
 * A general glossary of acting terms across stage, screen and voice.
 *
 * Plain data so it ships with the page (no DB, works offline once cached).
 * A term can carry several categories — "blocking" is both stage and screen.
 */

export const GLOSSARY_CATEGORIES = {
  craft: 'Technique & craft',
  stage: 'Stage',
  screen: 'Film & TV',
  voice: 'Voice acting',
  business: 'Auditions & business',
} as const;

export type GlossaryCategory = keyof typeof GLOSSARY_CATEGORIES;

export interface GlossaryTerm {
  term: string;
  definition: string;
  categories: GlossaryCategory[];
  /** Other names or spellings, also matched by search. */
  aka?: string[];
}

export const GLOSSARY: GlossaryTerm[] = [
  // ---------- Technique & craft ----------
  { term: 'Action', definition: 'What a character is actively doing to another person to get what they want, phrased as a playable verb (to charm, to belittle, to reassure). Also called a tactic in some methods.', categories: ['craft'], aka: ['Tactic'] },
  { term: 'Activity', definition: 'A physical task the actor performs during a scene (making tea, packing a bag) that gives the body something truthful to do while the scene plays out.', categories: ['craft'] },
  { term: 'Adjustment', definition: 'A change in approach to a scene or line, often given by a director or casting director to see if the actor can take direction.', categories: ['craft', 'business'] },
  { term: 'Affective memory', definition: 'Recalling a real past experience in sensory detail to produce genuine emotion on stage; central to Strasberg’s Method. Also called emotional memory or emotional recall.', categories: ['craft'], aka: ['Emotional memory', 'Emotional recall'] },
  { term: 'Arc', definition: 'The change a character goes through over a scene, episode or whole story.', categories: ['craft'], aka: ['Character arc'] },
  { term: 'As if', definition: 'A substitution technique: playing the scene “as if” it were a personal situation that produces the same stakes and feeling. Associated with Practical Aesthetics.', categories: ['craft'] },
  { term: 'Backstory', definition: 'The character’s history before the story begins — invented by the actor where the text is silent, to inform choices.', categories: ['craft'] },
  { term: 'Beat', definition: 'A unit of action within a scene; a new beat begins when the character’s intention or tactic shifts. (In a script, “beat” can also mean a brief pause.)', categories: ['craft'], aka: ['Unit'] },
  { term: 'Business', definition: 'Small physical actions an actor does with props or their body (adjusting a tie, shuffling papers) to add life and specificity.', categories: ['craft', 'stage'], aka: ['Stage business'] },
  { term: 'Chekhov technique', definition: 'Michael Chekhov’s approach to acting through imagination, atmosphere, and the psychological gesture — working from the outside in and the inside out at once.', categories: ['craft'], aka: ['Michael Chekhov technique'] },
  { term: 'Choice', definition: 'A specific decision about how to play a moment — what the character wants, how they pursue it, what it means to them. “Make a strong choice” is common audition advice.', categories: ['craft'] },
  { term: 'Cold read', definition: 'Reading from a script with little or no preparation, typically at an audition.', categories: ['craft', 'business'] },
  { term: 'Emotional preparation', definition: 'Work done before entering a scene to arrive already carrying the character’s emotional life (Meisner’s term for the actor’s pre-scene fantasy/daydream).', categories: ['craft'] },
  { term: 'Endowment', definition: 'Giving an object, person or place imagined qualities or history (a prop cup “is” your late mother’s) so the actor responds truthfully.', categories: ['craft'] },
  { term: 'Given circumstances', definition: 'The facts of the character’s situation supplied by the text — who, what, where, when and why. A Stanislavski concept.', categories: ['craft'] },
  { term: 'Hagen object exercises', definition: 'Uta Hagen’s exercises for building truthful behavior through specific, detailed tasks and substitution, from her book Respect for Acting.', categories: ['craft'], aka: ['Uta Hagen'] },
  { term: 'Indicating', definition: 'Showing the audience an emotion or idea instead of genuinely experiencing and pursuing it; usually a note to avoid.', categories: ['craft'], aka: ['Playing the result'] },
  { term: 'Inner monologue', definition: 'The character’s unspoken running thoughts, kept alive by the actor during a scene — especially while listening.', categories: ['craft'] },
  { term: 'Intention', definition: 'What the character wants to achieve in a moment or beat. Close to objective, sometimes used for smaller units.', categories: ['craft'] },
  { term: 'Listening', definition: 'Genuinely taking in your scene partner moment to moment so responses are truthful rather than pre-planned. Widely considered the heart of good acting.', categories: ['craft'] },
  { term: 'Magic if', definition: 'Stanislavski’s question: “What would I do if I were in these circumstances?” — a bridge between actor and character.', categories: ['craft'] },
  { term: 'Meisner technique', definition: 'Sanford Meisner’s approach built on “living truthfully under imaginary circumstances,” trained through the repetition exercise, independent activities and emotional preparation.', categories: ['craft'] },
  { term: 'Method acting', definition: 'Lee Strasberg’s American development of Stanislavski’s work, emphasizing sense memory and affective memory. Often loosely (and inaccurately) used to mean staying in character offstage.', categories: ['craft'], aka: ['The Method'] },
  { term: 'Moment before', definition: 'What was happening to the character immediately before the scene starts, so the actor enters mid-life rather than from zero.', categories: ['craft'] },
  { term: 'Motivation', definition: 'The reason behind a character’s action or want.', categories: ['craft'] },
  { term: 'Objective', definition: 'What the character wants — in a scene (scene objective) or over the whole story (super-objective). Best phrased as something you need from another person.', categories: ['craft'], aka: ['Want', 'Goal'] },
  { term: 'Obstacle', definition: 'Whatever stands between the character and their objective — another person, circumstance, or something inside themselves.', categories: ['craft'] },
  { term: 'Opposites', definition: 'Finding the contrary impulse within a moment (the laugh inside grief, the love inside a fight) to make a performance more complex and alive.', categories: ['craft'] },
  { term: 'Personalization', definition: 'Making the character’s circumstances personally meaningful to the actor, often through substitution.', categories: ['craft'] },
  { term: 'Physical score', definition: 'The planned, repeatable sequence of physical actions for a role or scene.', categories: ['craft'] },
  { term: 'Practical Aesthetics', definition: 'Technique developed by David Mamet and William H. Macy (Atlantic Theater Company) based on script analysis into literal action, the actor’s action, and the “as if.”', categories: ['craft'] },
  { term: 'Psychological gesture', definition: 'A Michael Chekhov tool: a full-body gesture that embodies the character’s core want or energy, used to find and hold the character.', categories: ['craft'], aka: ['PG'] },
  { term: 'Repetition exercise', definition: 'Meisner’s foundational exercise in which two actors repeat an observation back and forth, changing only as their genuine impulses change — training listening and response.', categories: ['craft'] },
  { term: 'Score', definition: 'An actor’s map of a role: beats, intentions, actions and key moments marked on the script.', categories: ['craft'], aka: ['Scoring a script'] },
  { term: 'Sense memory', definition: 'Recreating physical sensations (heat, taste, a smell) from memory so the body responds truthfully to imaginary circumstances.', categories: ['craft'] },
  { term: 'Stakes', definition: 'What the character stands to win or lose. Higher stakes generally produce more urgent, watchable playing.', categories: ['craft'] },
  { term: 'Stanislavski system', definition: 'Konstantin Stanislavski’s foundational system of actor training (given circumstances, objectives, magic if, through-line), the root of most modern Western technique.', categories: ['craft'], aka: ['Stanislavsky'] },
  { term: 'Status', definition: 'The relative power between characters in a moment, and how it shifts. A core idea in Keith Johnstone’s improv work.', categories: ['craft'] },
  { term: 'Subtext', definition: 'What a character really means or feels beneath the words they say.', categories: ['craft'] },
  { term: 'Substitution', definition: 'Replacing the character’s circumstance or person with one from the actor’s life that evokes a similar response.', categories: ['craft'] },
  { term: 'Super-objective', definition: 'The character’s overarching want across the entire story, which the scene objectives serve.', categories: ['craft'], aka: ['Spine'] },
  { term: 'Through-line', definition: 'The continuous line of action connecting a character’s objectives from beginning to end.', categories: ['craft'], aka: ['Through-line of action'] },
  { term: 'Viewpoints', definition: 'A movement and composition vocabulary (tempo, duration, kinesthetic response, shape, spatial relationship, etc.) developed by Mary Overlie and expanded by Anne Bogart and Tina Landau.', categories: ['craft', 'stage'] },
  { term: 'Laban efforts', definition: 'Rudolf Laban’s movement qualities — combinations of weight, time, space and flow (punch, float, glide, slash, dab, wring, press, flick) used to build physical characters.', categories: ['craft'] },
  { term: 'Neutral mask', definition: 'A training mask with no expression, used to strip away habit and develop an expressive, economical body. Associated with Jacques Lecoq.', categories: ['craft', 'stage'] },
  { term: 'Improvisation', definition: 'Performing without a script, responding spontaneously. Used as a performance form and as a rehearsal tool. “Yes, and” is its best-known principle.', categories: ['craft'], aka: ['Improv'] },
  { term: 'Yes, and', definition: 'Improv principle: accept what your partner offers (yes) and build on it (and).', categories: ['craft'] },
  { term: 'Offer', definition: 'In improv and scene work, anything a partner gives you — a line, a choice, a gesture — that you can accept and build on.', categories: ['craft'] },
  { term: 'Table read', definition: 'An early read-through of the script with the cast seated around a table.', categories: ['craft', 'stage', 'screen'], aka: ['Read-through'] },
  { term: 'Text analysis', definition: 'Close study of a script for facts, clues, structure, language and rhythm to inform choices.', categories: ['craft'], aka: ['Script analysis'] },
  { term: 'Operative word', definition: 'The most important word in a line — the one that carries the meaning and usually gets emphasis.', categories: ['craft', 'voice'] },
  { term: 'Iambic pentameter', definition: 'A line of verse with five iambs (da-DUM ×5), the dominant rhythm of Shakespeare’s verse. Its irregularities are clues for the actor.', categories: ['craft', 'stage'] },
  { term: 'Scansion', definition: 'Marking the stressed and unstressed syllables in verse to understand its rhythm.', categories: ['craft', 'stage'] },
  { term: 'Shared line', definition: 'In verse, a single line of meter split between two characters — traditionally a cue to pick up quickly with no pause.', categories: ['craft', 'stage'] },
  { term: 'Monologue', definition: 'An extended speech by one character, spoken to others or to themselves. Actors keep contrasting monologues ready for auditions.', categories: ['craft', 'business'] },
  { term: 'Soliloquy', definition: 'A speech in which a character alone on stage speaks their thoughts aloud.', categories: ['craft', 'stage'] },
  { term: 'Aside', definition: 'A brief remark to the audience that other characters on stage supposedly don’t hear.', categories: ['stage'] },
  { term: 'Breaking the fourth wall', definition: 'Directly acknowledging or addressing the audience (or camera).', categories: ['stage', 'screen'], aka: ['Direct address'] },
  { term: 'Fourth wall', definition: 'The imaginary wall between the performers and the audience in realistic performance.', categories: ['stage', 'screen'] },
  { term: 'Character work', definition: 'The process of building a character — voice, body, psychology, history — distinct from the actor.', categories: ['craft'] },
  { term: 'Physicality', definition: 'How a character carries and moves their body: posture, center, rhythm, gestures.', categories: ['craft', 'voice'] },
  { term: 'Center', definition: 'The part of the body a character seems to lead from (head, chest, pelvis), used to shape physical character.', categories: ['craft'] },
  { term: 'Tempo-rhythm', definition: 'Stanislavski’s term for the combined speed and inner pulse of a character or scene.', categories: ['craft'] },
  { term: 'Pace', definition: 'The overall speed and energy with which a scene is played; “pick up the pace” usually means tighten cues, not talk faster.', categories: ['craft', 'stage'] },
  { term: 'Pick up cues', definition: 'Respond without unnecessary gaps between the end of a partner’s line and the start of yours.', categories: ['craft', 'stage'] },
  { term: 'Emotional availability', definition: 'An actor’s openness to being affected in the moment.', categories: ['craft'] },
  { term: 'Presence', definition: 'The quality of being fully in the moment in a way that draws attention.', categories: ['craft'] },
  { term: 'Truthfulness', definition: 'Behavior that is believable and genuinely motivated within the imaginary circumstances.', categories: ['craft'] },
  { term: 'Playing against', definition: 'Choosing an approach that works against the obvious emotion of the text (playing a sad scene with humor), often more interesting and truthful.', categories: ['craft'] },
  { term: 'Dropping in', definition: 'A Shakespeare/text technique where a coach feeds key words and questions so the actor personally connects to the language before speaking it.', categories: ['craft'] },

  // ---------- Stage ----------
  { term: 'Upstage', definition: 'The part of the stage farthest from the audience. As a verb, to draw attention from another actor (or force them to turn away from the audience).', categories: ['stage'] },
  { term: 'Downstage', definition: 'The part of the stage closest to the audience.', categories: ['stage'] },
  { term: 'Stage left / stage right', definition: 'Left and right from the actor’s perspective facing the audience. House left/right is from the audience’s perspective.', categories: ['stage'], aka: ['Stage right'] },
  { term: 'House left / house right', definition: 'Left and right from the audience’s perspective — the reverse of stage left/right.', categories: ['stage'], aka: ['House right'] },
  { term: 'Center stage', definition: 'The middle of the playing area.', categories: ['stage'] },
  { term: 'Apron', definition: 'The part of the stage in front of the proscenium arch.', categories: ['stage'] },
  { term: 'Proscenium', definition: 'The arch framing the stage in a traditional theatre; a proscenium stage has the audience on one side.', categories: ['stage'] },
  { term: 'Thrust stage', definition: 'A stage extending into the audience, which sits on three sides.', categories: ['stage'] },
  { term: 'Theatre in the round', definition: 'A staging with the audience on all sides.', categories: ['stage'], aka: ['Arena stage'] },
  { term: 'Black box', definition: 'A flexible, usually small, unadorned performance space that can be configured many ways.', categories: ['stage'] },
  { term: 'Wings', definition: 'The offstage areas to the sides of the stage, hidden from the audience.', categories: ['stage'] },
  { term: 'Flies', definition: 'The space above the stage where scenery and lights are hung and raised.', categories: ['stage'], aka: ['Fly system', 'Fly loft'] },
  { term: 'Green room', definition: 'The lounge where performers wait when not on stage.', categories: ['stage', 'screen'] },
  { term: 'House', definition: 'The auditorium and the audience in it. “House is open” means the audience is being seated.', categories: ['stage'] },
  { term: 'Blocking', definition: 'The planned movement and positions of actors in a scene.', categories: ['stage', 'screen'] },
  { term: 'Cheat out', definition: 'Angle your body toward the audience (or camera) while still appearing to relate to your scene partner.', categories: ['stage', 'screen'], aka: ['Cheating'] },
  { term: 'Open up', definition: 'Turn more toward the audience so you can be seen and heard.', categories: ['stage'] },
  { term: 'Cross', definition: 'Moving from one part of the stage to another.', categories: ['stage'] },
  { term: 'Counter', definition: 'A small adjusting move to rebalance the stage picture when another actor crosses.', categories: ['stage'] },
  { term: 'Spike marks', definition: 'Tape marks on the stage floor showing where furniture, props or actors go.', categories: ['stage'], aka: ['Spike'] },
  { term: 'Cue', definition: 'The line, action or signal that prompts an actor’s line or entrance, or a technical change (lights, sound).', categories: ['stage', 'screen', 'voice'] },
  { term: 'Cue-to-cue', definition: 'A technical rehearsal that skips from one technical cue to the next, omitting dialogue in between.', categories: ['stage'], aka: ['Q2Q'] },
  { term: 'Tech rehearsal', definition: 'Rehearsals where lights, sound, set and effects are integrated with the performance. “Tech week” leads into previews or opening.', categories: ['stage'], aka: ['Tech week'] },
  { term: 'Dress rehearsal', definition: 'A full run in costume and makeup under performance conditions.', categories: ['stage'] },
  { term: 'Run-through', definition: 'Rehearsing the whole play (or an act) without stopping.', categories: ['stage'], aka: ['Run'] },
  { term: 'Stumble-through', definition: 'An early, rough run-through where stopping and prompts are expected.', categories: ['stage'] },
  { term: 'Italian run', definition: 'A run-through of the lines at high speed, usually without blocking, to cement memorization and pick up cues.', categories: ['stage'], aka: ['Speed-through'] },
  { term: 'Off book', definition: 'Having the lines memorized so you no longer carry the script.', categories: ['stage', 'screen'] },
  { term: 'Line!', definition: 'What an actor calls when they need a prompt from the stage manager during rehearsal.', categories: ['stage'] },
  { term: 'Prompt book', definition: 'The stage manager’s master script with all blocking, cues and notes.', categories: ['stage'], aka: ['Prompt script'] },
  { term: 'Stage manager', definition: 'The person who runs rehearsals’ logistics and calls the show during performances.', categories: ['stage'], aka: ['SM'] },
  { term: 'Places', definition: 'The call for actors to take their starting positions for the beginning of an act or show.', categories: ['stage'] },
  { term: 'Half hour', definition: 'The call 30 minutes before curtain, by which actors must be signed in at the theatre (typically 35 minutes before the stated curtain time).', categories: ['stage'] },
  { term: 'Call time', definition: 'The time an actor is required to arrive.', categories: ['stage', 'screen', 'voice'], aka: ['Call'] },
  { term: 'Sign-in sheet', definition: 'The backstage sheet actors initial on arrival.', categories: ['stage'] },
  { term: 'Curtain call', definition: 'The bows at the end of a performance.', categories: ['stage'], aka: ['Bows'] },
  { term: 'Notes', definition: 'Feedback from the director or others after a rehearsal or performance.', categories: ['stage', 'screen', 'voice'] },
  { term: 'Preview', definition: 'Public performances before the official opening, during which changes can still be made.', categories: ['stage'] },
  { term: 'Opening night', definition: 'The official first performance, typically when reviews are published.', categories: ['stage'] },
  { term: 'Understudy', definition: 'An actor who learns a role (while usually playing a smaller one) and performs it when the principal is out.', categories: ['stage'] },
  { term: 'Swing', definition: 'An offstage performer in a musical who covers multiple ensemble tracks.', categories: ['stage'] },
  { term: 'Standby', definition: 'An offstage performer who covers a principal role but doesn’t perform in the show nightly.', categories: ['stage'] },
  { term: 'Track', definition: 'The full sequence of roles, entrances and duties a particular performer has in a show, especially in musicals.', categories: ['stage'] },
  { term: 'Ensemble', definition: 'The group of performers who aren’t principals, or the whole company working together.', categories: ['stage'], aka: ['Chorus'] },
  { term: 'Put-in rehearsal', definition: 'A rehearsal to integrate a replacement or understudy into a running show.', categories: ['stage'], aka: ['Put-in'] },
  { term: 'Hold (stage)', definition: 'A pause in action (e.g. for a laugh or applause), or a technical hold before a show starts.', categories: ['stage'] },
  { term: 'Hold for laughs', definition: 'Pausing so the audience’s laughter doesn’t swallow the next line.', categories: ['stage'] },
  { term: 'Projection', definition: 'Supporting the voice so it carries to the back of the house without strain.', categories: ['stage', 'voice'] },
  { term: 'Diction', definition: 'Clarity of speech and pronunciation.', categories: ['stage', 'voice'], aka: ['Articulation'] },
  { term: 'Corpsing', definition: 'Breaking character by laughing unintentionally on stage (British term).', categories: ['stage', 'screen'], aka: ['Breaking'] },
  { term: 'Upstaging', definition: 'Stealing focus from another actor, or positioning upstage so they must turn away from the audience.', categories: ['stage'] },
  { term: 'Sightlines', definition: 'The audience’s lines of view to the stage; actors must stay within them to be seen.', categories: ['stage'] },
  { term: 'Stage picture', definition: 'The overall composition of actors and set as seen by the audience.', categories: ['stage'] },
  { term: 'Strike', definition: 'To remove something from the stage; also the dismantling of the set after a production closes.', categories: ['stage', 'screen'] },
  { term: 'Props', definition: 'Objects handled by actors. Personal props belong to one character; a prop table holds them offstage.', categories: ['stage', 'screen'], aka: ['Properties'] },
  { term: 'Break a leg', definition: 'Traditional good-luck wish before a performance — saying “good luck” is considered bad luck.', categories: ['stage'] },
  { term: 'The Scottish play', definition: 'How superstitious theatre people refer to Macbeth inside a theatre, to avoid bad luck.', categories: ['stage'] },
  { term: 'Ghost light', definition: 'A single light left burning on an empty stage overnight, for safety (and tradition).', categories: ['stage'] },
  { term: 'Dark', definition: 'A theatre with no performance scheduled (“the theatre is dark on Mondays”).', categories: ['stage'] },
  { term: 'Equity', definition: 'Actors’ Equity Association (US stage actors’ union), or Equity in the UK, which covers stage and screen.', categories: ['stage', 'business'], aka: ['AEA', 'Actors’ Equity'] },
  { term: 'Equity Principal Audition (EPA)', definition: 'A required open audition for Equity members for principal roles in Equity productions.', categories: ['stage', 'business'], aka: ['EPA'] },
  { term: 'ECC', definition: 'Equity Chorus Call — an open audition for chorus/ensemble in Equity productions.', categories: ['stage', 'business'], aka: ['Equity Chorus Call'] },
  { term: 'Open call', definition: 'An audition open to anyone, without an appointment.', categories: ['stage', 'business'], aka: ['Cattle call'] },
  { term: '16 bars', definition: 'A short cut of a song (roughly 16 measures) requested at musical theatre auditions; “32 bars” is the longer version.', categories: ['stage', 'business'], aka: ['32 bars'] },
  { term: 'Book (musical)', definition: 'The spoken dialogue and story of a musical, as distinct from the score.', categories: ['stage'], aka: ['Libretto'] },
  { term: 'Sitzprobe', definition: 'The first rehearsal where the cast sings with the orchestra, focusing on music rather than staging.', categories: ['stage'] },
  { term: 'Wandelprobe', definition: 'A rehearsal with the orchestra where the cast also runs the staging.', categories: ['stage'] },

  // ---------- Film & TV ----------
  { term: 'Action!', definition: 'The director’s call to begin performing a take.', categories: ['screen'] },
  { term: 'Cut!', definition: 'The call to stop a take. Keep playing until you hear it.', categories: ['screen'] },
  { term: 'Rolling / speed', definition: 'Calls confirming the camera and sound are recording before “action.”', categories: ['screen'], aka: ['Speed', 'Rolling'] },
  { term: 'Back to one', definition: 'Return to your starting position for another take.', categories: ['screen'] },
  { term: 'Checking the gate', definition: 'Confirming the camera captured the shot cleanly before moving on.', categories: ['screen'] },
  { term: 'Moving on', definition: 'The shot is done; the crew moves to the next setup.', categories: ['screen'] },
  { term: 'Setup', definition: 'Each new camera position and lighting arrangement.', categories: ['screen'] },
  { term: 'Take', definition: 'One recorded attempt at a shot (or, in VO, a line). Takes are numbered.', categories: ['screen', 'voice'] },
  { term: 'Coverage', definition: 'All the angles shot of a scene (wides, mediums, close-ups, reverses) so the editor has options.', categories: ['screen'] },
  { term: 'Master shot', definition: 'A wide shot capturing the whole scene, usually shot first.', categories: ['screen'], aka: ['Master'] },
  { term: 'Close-up', definition: 'A shot framing the face; requires very contained, specific playing.', categories: ['screen'], aka: ['CU', 'ECU'] },
  { term: 'Medium shot', definition: 'A shot framing roughly waist up.', categories: ['screen'], aka: ['MS', 'Mid shot'] },
  { term: 'Wide shot', definition: 'A shot showing the full body and surroundings.', categories: ['screen'], aka: ['WS', 'Long shot'] },
  { term: 'Two-shot', definition: 'A shot framing two actors.', categories: ['screen'] },
  { term: 'Over-the-shoulder', definition: 'A shot framed over one actor’s shoulder onto the other.', categories: ['screen'], aka: ['OTS'] },
  { term: 'Reverse', definition: 'The opposite angle of a shot, typically the other actor’s coverage in a conversation.', categories: ['screen'] },
  { term: 'Insert', definition: 'A close shot of a detail (a hand, a phone screen) cut into a scene.', categories: ['screen'] },
  { term: 'Eyeline', definition: 'Where an actor looks during a shot; matching eyelines keeps the edit coherent.', categories: ['screen'] },
  { term: 'Hitting your mark', definition: 'Arriving precisely at your tape mark so you stay in focus and frame.', categories: ['screen'], aka: ['Mark'] },
  { term: 'Continuity', definition: 'Keeping actions, props, costume and positions consistent between takes so shots cut together. A script supervisor tracks it.', categories: ['screen'], aka: ['Matching'] },
  { term: 'Script supervisor', definition: 'Crew member who tracks continuity, dialogue changes and what was shot.', categories: ['screen'], aka: ['Scripty'] },
  { term: 'First AD', definition: 'The first assistant director, who runs the set, schedule and calls.', categories: ['screen'], aka: ['1st AD', 'Assistant director'] },
  { term: 'Second AD', definition: 'Assistant director who handles cast logistics, call sheets and getting actors to set.', categories: ['screen'], aka: ['2nd AD'] },
  { term: 'Call sheet', definition: 'The daily schedule listing call times, scenes, locations and cast.', categories: ['screen'] },
  { term: 'Sides', definition: 'The pages of script for the scenes being auditioned or shot that day.', categories: ['screen', 'business', 'stage'] },
  { term: 'Pages', definition: 'Script pages; “we’re shooting six pages today.” Scenes are timed in eighths of a page.', categories: ['screen'] },
  { term: 'Blocking rehearsal', definition: 'A walkthrough on set to set positions and moves before lighting.', categories: ['screen'] },
  { term: 'Marking', definition: 'Walking through a scene at low energy for technical purposes, saving the full performance for the take.', categories: ['screen', 'stage'] },
  { term: 'Stand-in', definition: 'A person who takes an actor’s place while lighting and camera are set up.', categories: ['screen'], aka: ['Second team'] },
  { term: 'First team / second team', definition: 'The principal actors (first team) versus their stand-ins (second team).', categories: ['screen'], aka: ['First team'] },
  { term: 'Background', definition: 'Extras — performers who appear in scenes without lines.', categories: ['screen'], aka: ['Extras', 'BG'] },
  { term: 'Day player', definition: 'An actor hired on a daily basis, usually for a small speaking role.', categories: ['screen', 'business'] },
  { term: 'Co-star', definition: 'A small role in US television, typically a few lines in one episode.', categories: ['screen', 'business'] },
  { term: 'Guest star', definition: 'A larger one-episode (or few-episode) TV role, above co-star.', categories: ['screen', 'business'] },
  { term: 'Recurring', definition: 'A TV role that appears across multiple episodes without being series regular.', categories: ['screen', 'business'] },
  { term: 'Series regular', definition: 'A main cast member contracted for all or most episodes of a TV series.', categories: ['screen', 'business'] },
  { term: 'Under-five', definition: 'A US TV/soap role with five lines or fewer.', categories: ['screen', 'business'], aka: ['U/5'] },
  { term: 'Principal', definition: 'A performer with a speaking or featured role (as opposed to background).', categories: ['screen', 'business'] },
  { term: 'ADR', definition: 'Automated Dialogue Replacement: re-recording dialogue in a studio to sync with picture after filming.', categories: ['screen', 'voice'], aka: ['Looping', 'Dubbing'] },
  { term: 'Wild line', definition: 'A line recorded by sound without camera rolling, to be edited in later.', categories: ['screen', 'voice'] },
  { term: 'Room tone', definition: 'A recording of a location’s ambient silence, used to smooth audio edits. Everyone holds still for it.', categories: ['screen', 'voice'] },
  { term: 'Pickups', definition: 'Additional shots or lines filmed/recorded after the main shoot to fix or complete material.', categories: ['screen', 'voice'] },
  { term: 'Martini shot', definition: 'The last shot of the day.', categories: ['screen'] },
  { term: 'Abby Singer', definition: 'The second-to-last shot of the day.', categories: ['screen'] },
  { term: 'Wrap', definition: 'The end of shooting — for the day, for an actor (“series wrap”), or for the production.', categories: ['screen'] },
  { term: 'Dailies', definition: 'The raw footage from a day of shooting, reviewed by the director and producers.', categories: ['screen'], aka: ['Rushes'] },
  { term: 'Frame', definition: 'The boundaries of the shot. Small movements can take you “out of frame.”', categories: ['screen'] },
  { term: 'Holding', definition: 'The waiting area for background actors on set.', categories: ['screen'] },
  { term: 'Honeywagon', definition: 'A trailer with small dressing rooms (and restrooms) for cast on location.', categories: ['screen'] },
  { term: 'Chroma key', definition: 'Shooting against a green or blue screen so the background can be replaced digitally.', categories: ['screen'], aka: ['Green screen'] },
  { term: 'Motion capture', definition: 'Recording an actor’s movement (and often face) with sensors or markers to drive a digital character.', categories: ['screen', 'voice'], aka: ['Mocap', 'Performance capture'] },
  { term: 'Tennis ball', definition: 'A stand-in eyeline marker for a CG character or element that isn’t physically there.', categories: ['screen'] },
  { term: 'Sitcom (multi-cam)', definition: 'A comedy shot with several cameras at once, often before a live audience; more theatrical in rhythm than single-cam.', categories: ['screen'], aka: ['Multi-cam'] },
  { term: 'Single-cam', definition: 'A production shot with one camera setup at a time, like film.', categories: ['screen'] },

  // ---------- Voice acting ----------
  { term: 'Voice over (VO)', definition: 'Voice performance recorded separately from picture — commercials, narration, animation, games, and more.', categories: ['voice'], aka: ['VO', 'Voiceover'] },
  { term: 'Booth', definition: 'The acoustically treated room where a voice actor records.', categories: ['voice'], aka: ['Vocal booth'] },
  { term: 'Control room', definition: 'Where the engineer, director and clients listen and run the session.', categories: ['voice'] },
  { term: 'Talkback', definition: 'The intercom system the director and engineer use to speak to the actor in the booth.', categories: ['voice'] },
  { term: 'Engineer', definition: 'The person who runs the recording equipment and session, and often edits and labels takes.', categories: ['voice'], aka: ['Audio engineer'] },
  { term: 'Session director', definition: 'The person directing the actor’s performance in a VO session.', categories: ['voice'], aka: ['Voice director'] },
  { term: 'Slate', definition: 'Saying your name (and sometimes role or agency) at the start of an audition. In VO, many casting sites now ask you not to slate — follow the specs.', categories: ['voice', 'business', 'screen'] },
  { term: 'Specs', definition: 'The character description and direction supplied with a VO audition — age, vibe, sound, references.', categories: ['voice', 'business'] },
  { term: 'Copy', definition: 'The script text in VO, especially commercial.', categories: ['voice'] },
  { term: 'Read', definition: 'A performance of the copy. “Give me a warmer read.”', categories: ['voice'] },
  { term: 'Pickup (VO)', definition: 'Re-recording part of a line or script, e.g. “pick it up from ‘but wait.’”', categories: ['voice'] },
  { term: 'Punch-in', definition: 'Recording over a specific section while the rest of the take plays back, so you fit seamlessly into it.', categories: ['voice'], aka: ['Punch and roll'] },
  { term: 'Three takes / three reads', definition: 'A common VO practice (especially in games) of recording each line in three quick variations.', categories: ['voice'], aka: ['Threes'] },
  { term: 'Wild takes', definition: 'Recording several takes in a row without stopping between them.', categories: ['voice'] },
  { term: 'Safety take', definition: 'An extra take recorded after a good one, just in case.', categories: ['voice', 'screen'], aka: ['One for safety'] },
  { term: 'Placement', definition: 'Where the voice seems to resonate (nasal/mask, head, mouth, throat, chest) — one of the main levers for creating character voices.', categories: ['voice'] },
  { term: 'Resonance', definition: 'How the voice is amplified and colored by the spaces of the throat, mouth and nose.', categories: ['voice'] },
  { term: 'Pitch', definition: 'How high or low the voice sits.', categories: ['voice'] },
  { term: 'Timbre', definition: 'The tonal color or quality of a voice independent of pitch and volume.', categories: ['voice'], aka: ['Tone color'] },
  { term: 'Vocal fry', definition: 'A low, creaky register produced with loosely closed vocal folds. Useful in small doses; can tire the voice if overused.', categories: ['voice'], aka: ['Creak'] },
  { term: 'Rasp', definition: 'A gritty, rough vocal texture. Should be produced with safe technique (distortion placement, support), not by squeezing the throat.', categories: ['voice'], aka: ['Grit', 'Distortion'] },
  { term: 'Breath support', definition: 'Controlled use of breath from the body’s core to power the voice without throat strain.', categories: ['voice', 'stage'], aka: ['Support'] },
  { term: 'Proximity effect', definition: 'The bass boost you get as you move closer to a directional microphone. Voice actors work the mic distance intentionally.', categories: ['voice'] },
  { term: 'Working the mic', definition: 'Adjusting distance and angle to the microphone to match volume and intimacy — closer for whispers, back and off-axis for shouts.', categories: ['voice'] },
  { term: 'Off-mic / off-axis', definition: 'Turning or moving away from the microphone’s pickup pattern, e.g. to avoid overloading on loud efforts or to sound distant.', categories: ['voice'], aka: ['Off-axis'] },
  { term: 'Plosive', definition: 'A burst of air from sounds like P and B that “pops” the mic. Pop filters and slight off-axis positioning help.', categories: ['voice'], aka: ['P-pop'] },
  { term: 'Sibilance', definition: 'Harsh, hissy S and SH sounds on a recording.', categories: ['voice'] },
  { term: 'Mouth noise', definition: 'Clicks, smacks and saliva sounds picked up by the mic. Hydration (and green apples) help.', categories: ['voice'], aka: ['Mouth clicks'] },
  { term: 'Pop filter', definition: 'A screen between the mouth and mic that softens plosives.', categories: ['voice'] },
  { term: 'Noise floor', definition: 'The level of background noise in a recording when no one is speaking; lower is better.', categories: ['voice'] },
  { term: 'Clipping', definition: 'Digital distortion caused when the signal exceeds the maximum level — unfixable, so leave headroom.', categories: ['voice'] },
  { term: 'Headroom', definition: 'The margin between your loudest peaks and the clipping point.', categories: ['voice'] },
  { term: 'Gain', definition: 'Input level on your interface or preamp; set so your loudest takes don’t clip.', categories: ['voice'] },
  { term: 'Audio interface', definition: 'A device that connects a microphone to a computer and converts the signal to digital.', categories: ['voice'] },
  { term: 'DAW', definition: 'Digital Audio Workstation — recording and editing software (Audacity, Reaper, Twisted Wave, Pro Tools, Adobe Audition, etc.).', categories: ['voice'], aka: ['Digital audio workstation'] },
  { term: 'Home studio', definition: 'A voice actor’s own treated recording space and gear, standard for auditions and much remote work.', categories: ['voice', 'business'] },
  { term: 'Source-Connect', definition: 'Software for recording remotely at broadcast quality with a studio. ipDTL and similar tools serve the same purpose.', categories: ['voice', 'business'], aka: ['ipDTL', 'Remote session'] },
  { term: 'Directed session', definition: 'A remote or in-studio session with a director and/or client listening live and giving direction.', categories: ['voice'] },
  { term: 'Self-directed', definition: 'Recording and delivering on your own without live direction, common for auditions and some jobs.', categories: ['voice'] },
  { term: 'Efforts', definition: 'Non-verbal vocal sounds — attacks, hits, jumps, deaths, breaths, grunts. A staple of game and animation sessions.', categories: ['voice'], aka: ['Vocal efforts', 'Exertions'] },
  { term: 'Barks', definition: 'Short, repeatable in-game lines triggered by gameplay (callouts like “Reloading!”).', categories: ['voice'] },
  { term: 'Callout', definition: 'A bark communicating tactical info to the player or squad (“Enemy left!”).', categories: ['voice'] },
  { term: 'Walla', definition: 'Crowd and background vocal ambience; indistinct murmur and small lines recorded by a group.', categories: ['voice', 'screen'], aka: ['Loop group', 'Group ADR'] },
  { term: 'Loop group', definition: 'A team of actors who record walla and background voices in post-production.', categories: ['voice', 'screen'] },
  { term: 'Lip flap', definition: 'The mouth movement of an animated or filmed character that dialogue must match — the key constraint in dubbing.', categories: ['voice'], aka: ['Flaps', 'Mouth flaps'] },
  { term: 'Pre-lay / pre-recorded', definition: 'Animation (typical in US TV) where voices are recorded first and animated to afterwards, giving actors more freedom.', categories: ['voice'], aka: ['Pre-lay'] },
  { term: 'Post-sync', definition: 'Recording voices to already-finished animation or footage, matching timing and flaps — how most anime dubs are done.', categories: ['voice'], aka: ['Post-lay'] },
  { term: 'Dubbing', definition: 'Replacing dialogue with a new-language (or new) performance matched to picture.', categories: ['voice', 'screen'] },
  { term: 'Beeps', definition: 'Audible count-in tones (commonly three) that cue the exact start of a line when recording to picture.', categories: ['voice'], aka: ['Three beeps'] },
  { term: 'Rythmo band', definition: 'A scrolling text track under the picture showing exactly when each syllable must be spoken; used widely in French and Canadian dubbing.', categories: ['voice'], aka: ['Bande rythmo'] },
  { term: 'Time-constrained line', definition: 'A game line that must fit a set duration (for cinematics, lip-sync or localization). Often shown as “max length” in the script.', categories: ['voice'], aka: ['Timed line'] },
  { term: 'Line ID', definition: 'The unique identifier for each line in a game script spreadsheet, used to track and name recorded files.', categories: ['voice'] },
  { term: 'Context (game VO)', definition: 'The note beside a game line explaining the situation, since game lines are recorded out of order and often without the scene around them.', categories: ['voice'] },
  { term: 'Pickup session', definition: 'A later session to re-record or add lines after the main record.', categories: ['voice'] },
  { term: 'Vocal stress / vocally stressful', definition: 'Sessions heavy in screaming, efforts or creature sounds. SAG-AFTRA’s Interactive Media Agreement limits the length of vocally stressful sessions.', categories: ['voice', 'business'], aka: ['Vocally stressful session'] },
  { term: 'Creature voice', definition: 'Non-human vocalizations — monsters, animals, aliens — that often use distortion and false-fold techniques.', categories: ['voice'] },
  { term: 'Character voice', definition: 'A voice distinctly different from the actor’s natural voice, built from choices of pitch, placement, texture, pace and attitude.', categories: ['voice'] },
  { term: 'Real person voice', definition: 'A conversational, natural read with no “announcer” quality — the dominant commercial style today.', categories: ['voice'], aka: ['Conversational read'] },
  { term: 'Announcer', definition: 'A projected, polished, presentational VO style.', categories: ['voice'] },
  { term: 'Tag', definition: 'The closing line of a commercial, often with the brand name or offer, sometimes recorded separately.', categories: ['voice'] },
  { term: 'Donut', definition: 'A commercial with music at the start and end and a hole in the middle for VO (or vice versa).', categories: ['voice'] },
  { term: 'Narration', definition: 'Storytelling or informational VO — documentaries, corporate, e-learning.', categories: ['voice'] },
  { term: 'Audiobook', definition: 'Long-form narration of a book, often voicing multiple characters.', categories: ['voice'] },
  { term: 'Finished hours', definition: 'In audiobooks, the length of the final edited product, which is how narrators are usually paid (PFH: per finished hour).', categories: ['voice', 'business'], aka: ['PFH', 'Per finished hour'] },
  { term: 'Demo reel (VO)', definition: 'A short compilation of your voice work by genre — commercial, animation, video game, narration — each usually around a minute.', categories: ['voice', 'business'], aka: ['VO demo', 'Voice demo'] },
  { term: 'Pay-to-play', definition: 'Online casting marketplaces that charge talent a membership fee to audition (e.g. Voices.com, Voice123).', categories: ['voice', 'business'], aka: ['P2P'] },
  { term: 'Usage', definition: 'Where, how long, and in what media a recording may be used; it drives commercial VO rates.', categories: ['voice', 'business', 'screen'] },
  { term: 'Buyout', definition: 'A one-time payment covering broad or unlimited use of a recording, instead of ongoing residuals.', categories: ['voice', 'business'] },
  { term: 'AI / synthetic voice clause', definition: 'Contract language governing whether your voice can be used to train or create digital replicas. Read these carefully; unions have specific protections.', categories: ['voice', 'business'], aka: ['Digital replica'] },

  // ---------- Auditions & business ----------
  { term: 'Agent', definition: 'A licensed representative who submits you for work and negotiates bookings, typically for a percentage (commonly 10% for union work in the US).', categories: ['business'], aka: ['Talent agent'] },
  { term: 'Manager', definition: 'A representative who guides career strategy and development, often commissioning 10–20%. Not licensed to book work in some places.', categories: ['business'], aka: ['Talent manager'] },
  { term: 'Casting director', definition: 'The person who finds and recommends actors for roles on behalf of producers and directors.', categories: ['business'], aka: ['CD'] },
  { term: 'Casting associate', definition: 'Works under the casting director, often running sessions and reviewing tapes.', categories: ['business'] },
  { term: 'Breakdown', definition: 'The list of roles being cast, with character descriptions, sent to agents and posted on casting sites.', categories: ['business'], aka: ['Casting breakdown'] },
  { term: 'Submission', definition: 'Putting yourself (or your agent putting you) forward for a role.', categories: ['business'] },
  { term: 'Self-tape', definition: 'An audition you record yourself and submit, now standard for screen and increasingly stage.', categories: ['business', 'screen'], aka: ['Self tape', 'Taped audition'] },
  { term: 'Reader', definition: 'The person reading the other characters’ lines opposite you in an audition or self-tape. Should be off-camera and quieter than you.', categories: ['business', 'screen'] },
  { term: 'Pre-read', definition: 'A first audition with the casting director before you’re brought to producers.', categories: ['business'] },
  { term: 'Callback', definition: 'A follow-up audition after the first one.', categories: ['business'] },
  { term: 'Producer session', definition: 'A callback in front of producers and/or the director.', categories: ['business'] },
  { term: 'Chemistry read', definition: 'An audition pairing actors to see how they play together.', categories: ['business', 'screen'], aka: ['Chemistry test'] },
  { term: 'Screen test', definition: 'A filmed audition, often at the final stage, sometimes in costume.', categories: ['business', 'screen'], aka: ['Test deal'] },
  { term: 'Avail', definition: 'A check on whether an actor is available for certain dates; not a booking.', categories: ['business'], aka: ['Availability check'] },
  { term: 'First refusal', definition: 'A hold request: you’re asked to offer the production first chance before accepting other work on those dates.', categories: ['business'] },
  { term: 'Hold (booking)', definition: 'A request that you keep dates free because you’re under consideration or likely booked; not yet a confirmed booking.', categories: ['business'], aka: ['On hold', 'Pin'] },
  { term: 'Pinned', definition: 'Being held under consideration after an audition while casting decides.', categories: ['business'] },
  { term: 'Booking', definition: 'Getting the job.', categories: ['business'] },
  { term: 'Offer only', definition: 'A role offered directly without audition, usually to established actors.', categories: ['business'] },
  { term: 'Headshot', definition: 'A professional photo of your face that shows who you are and how you might be cast.', categories: ['business'] },
  { term: 'Résumé', definition: 'An acting CV listing credits, training and special skills, formatted to industry conventions.', categories: ['business'], aka: ['Resume', 'CV'] },
  { term: 'Reel', definition: 'A short video compilation of your best on-camera work.', categories: ['business', 'screen'], aka: ['Demo reel', 'Showreel'] },
  { term: 'Type', definition: 'The kinds of roles you’re most readily cast as, based on look, age range and energy.', categories: ['business'] },
  { term: 'Typecasting', definition: 'Repeatedly casting an actor in similar roles.', categories: ['business'] },
  { term: 'Brand', definition: 'A clear sense of the roles and qualities you’re known for, used to target marketing and submissions.', categories: ['business'] },
  { term: 'Age range', definition: 'The span of ages you can believably play.', categories: ['business'], aka: ['Playing range'] },
  { term: 'Special skills', definition: 'Résumé section for abilities (dialects, instruments, sports, combat) that could get you cast.', categories: ['business'] },
  { term: 'Casting sites', definition: 'Platforms where roles are posted and submitted to (e.g. Actors Access, Casting Networks, Backstage, Spotlight in the UK).', categories: ['business'] },
  { term: 'SAG-AFTRA', definition: 'US union representing screen actors, broadcasters, recording artists and voice actors (including games under the Interactive Media Agreement).', categories: ['business', 'screen', 'voice'], aka: ['SAG', 'AFTRA'] },
  { term: 'Taft-Hartley', definition: 'A provision allowing a non-union performer to work a SAG-AFTRA job, which can lead to union eligibility.', categories: ['business'] },
  { term: 'Fi-Core', definition: 'Financial core status: a union member who pays reduced dues and can work non-union jobs, with loss of union membership rights. Controversial.', categories: ['business'], aka: ['Financial core'] },
  { term: 'Scale', definition: 'The union minimum rate for a job; “scale plus ten” covers the agent’s commission on top.', categories: ['business'], aka: ['Scale plus ten'] },
  { term: 'Residuals', definition: 'Ongoing payments for reruns or continued use of a performance under union contracts.', categories: ['business', 'screen', 'voice'] },
  { term: 'Holding fee', definition: 'A payment to keep a commercial performer’s work available for use over a cycle.', categories: ['business'] },
  { term: 'Session fee', definition: 'Payment for the time spent recording or shooting, separate from usage.', categories: ['business', 'voice'] },
  { term: 'Exclusivity', definition: 'A contract term preventing you from working for competing brands or projects for a set time.', categories: ['business'] },
  { term: 'Deal memo', definition: 'A short agreement outlining the key terms of a booking before the full contract.', categories: ['business'] },
  { term: 'Billing', definition: 'Where and how your name appears in credits and publicity.', categories: ['business'] },
  { term: 'Commission', definition: 'The percentage of your pay that an agent or manager takes.', categories: ['business'] },
  { term: 'General meeting', definition: 'A get-to-know-you meeting with a casting director, producer or agent not tied to a specific role.', categories: ['business'], aka: ['General'] },
  { term: 'Showcase', definition: 'A performance of scenes presented for agents and casting directors, often at the end of training.', categories: ['business'] },
  { term: 'Fitting', definition: 'A costume appointment before shooting or performing.', categories: ['business', 'screen', 'stage'], aka: ['Wardrobe fitting'] },
  { term: 'Hold harmless', definition: 'Contract language releasing one party from liability — read before signing.', categories: ['business'] },
];
